// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RCPP_wedge_H_GEN_
#define RCPP_wedge_H_GEN_

#include "wedge_RcppExports.h"

#endif // RCPP_wedge_H_GEN_
