# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

wedgeRcpp <- function(a1, b1, a2, b2, size_vect, tau, N, lower_tail) {
    .Call('wedge_wedgeRcpp', PACKAGE = 'wedge', a1, b1, a2, b2, size_vect, tau, N, lower_tail)
}

